spring:
  application:
    name: app

  datasource:
    url: jdbc:postgresql://localhost:5432/task_store
    username: 'root'
    password: '0000'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true