spring:
  application:
    name: auth

#
#  datasource:
#    url: jdbc:postgresql://localhost:5050/db
#    username: 'root'
#    password: '0000'
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true

security:
  jwt:
    secret-key: "jw/0z3nU8gLGl+zKO7p2n1CUbrPWveCUgt8hzSwPqbY="
    expiration-time: 3600000
  app-name : "auth-app"

server:
  port: 5000